# Generated by Django 2.0.7 on 2019-06-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_premium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('tenure', models.IntegerField()),
            ],
        ),
    ]
