# Generated by Django 2.0.7 on 2019-06-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_premium', '0002_company1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company1',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dummy',
            name='tenure',
            field=models.IntegerField(default=0),
        ),
    ]
