# Generated by Django 2.0.7 on 2019-06-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_premium', '0003_auto_20190624_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='company1',
            name='value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company1',
            name='tenure',
            field=models.IntegerField(blank=True),
        ),
    ]
