# Generated by Django 2.0.7 on 2019-06-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_premium', '0004_auto_20190625_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company1',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='company1',
            name='tenure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company1',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=200, null=True),
        ),
    ]
