# Generated by Django 2.0.7 on 2019-06-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_premium', '0007_company2_company3'),
    ]

    operations = [
        migrations.CreateModel(
            name='company4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0, null=True)),
                ('tenure', models.IntegerField(blank=True, null=True)),
                ('value', models.FloatField(null=True)),
            ],
        ),
    ]
