# Generated by Django 2.0.7 on 2019-07-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_premium', '0008_company4'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='documents',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
