# Generated by Django 2.0.7 on 2019-07-15 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_premium', '0011_auto_20190713_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company1',
        ),
        migrations.DeleteModel(
            name='company2',
        ),
        migrations.DeleteModel(
            name='company3',
        ),
        migrations.DeleteModel(
            name='company4',
        ),
        migrations.DeleteModel(
            name='dummy',
        ),
    ]
